### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by piensd** [jurgo4509/CookieCutter#2]
### ok your project lacks assembly and your code is unoptimized (its kinda bruh)
[https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Trollface_non-free.png/220px-Trollface_non-free.png](url)
can you pls fix the issue where your extension crashes my pc?

**Comment by piensd** [comment]
bruh the trollface is not working

**Comment by piensd** [comment]
![this pic goes so hard](https://user-images.githubusercontent.com/97181890/204925947-6266492b-333c-4dda-9858-47e5d1765d8b.jpg)

**Comment by piensd** [comment]
ok its good now no worrys

**Comment by piensd** [comment]
!
![obama](https://user-images.githubusercontent.com/97181890/204926164-7029d9a7-c9bb-4063-b5d9-3b494d90296d.jpg)
[bbbb](https://user-images.githubusercontent.com/97181890/2049
![discord mod](https://user-images.githubusercontent.com/97181890/2049261
![arhombus](https://user-images.githubusercontent.com/97181890/204926193-cf12ea62-ac52-44b6-889d-ca89b83253ad.png)
75-756b91d3-5401-4d41-9f6b-f3ef0d043f4c.gif)
![trapezoid](https://user-images.githubusercontent.com/97181890/204926205-a2ae67e8-d180-4011-8814-07a10d967845.png)

26146-6242d57d-3200-45ca-98be-3ac1b9f169c4.jpg)

**Comment by jurgo4509** [comment]
![trollface](https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Trollface_non-free.png/220px-Trollface_non-free.png)
### Clearly it works
###### Dumbass
