### ISSUE TITLE
tit(le)

### ISSUE THREAD

**Issue by piensd** [jurgo4509/CookieCutter#3]
![myreaction](https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Trollface_non-free.png/220px-Trollface_non-free.png)

**Comment by klappscheinwerfer** [comment]
Yes

**Comment by piensd** [comment]
@jurgo4509

**Comment by piensd** [comment]
fix this shit bruh

**Comment by piensd** [comment]
your code is fucked up bruh
